### PR TITLE
Missing rvm_scripts_path fixed

### PR DESCRIPTION
**Pull request by diasjorge**
The ENV variable is missing, fixed in the patch

### CODE REVIEW

**Comment by deardaniel** [comment]
This needs pulled into master.

**Comment by ghost** [comment]
Care to pull this? Just experienced this error. Making my unable to use your completion file.

Please pull! ;) Thank you.

**Comment by cczona** [comment]
Bump.  Same error for me too "Failed to find rvm scripts path - is rvm installed correctly?"

rvm completion v0.2.1
rvm 1.16.5
OSX 10.8.2

**Comment by diasjorge** [comment]
ok closing since this never got merged.

**Pull request closed without merging**
